---
title: "Effort_wrangling"
author: "Dustin Duncan"
format: html
editor: visual
---

## This script is dedicated to viewing the effort data for Liberia

Citation: Rousseau, Y., Blanchard, J. L., Novaglio, C., Pinnell, K. A., Tittensor, D. P., Watson, R. A., & Ye, Y. (2024). A database of mapped global fishing activity 1950–2017. Scientific Data, 11(1), 48.

```{r}
# rm(list = ls())
library(tidyverse)
```

```{r}
effort_mapped = read_csv(("../../mapped_430.csv"))
all_metrics = read.csv(here::here("data_int/data_FAO/all_metrics_timeseries_1997_2017.csv"))
```

```{r}
## Looking at different fish groups present in the dataframe 
unique(effort_mapped$FGroup) 
 

## Unfortunately its wide fish groups... gonna say pelagics <30cm because thats what Sea Around us cites the Round Sardinella as, and also filter the year to after the civil war 
effort_filt = effort_mapped %>% 
  filter(Year >= 2003) %>% 
  filter(FGroup %in% c("pelagic<30cm"))

## Now looking at gear 
unique(effort_filt$Gear)

effort_gear_filt = effort_filt %>% 
  filter(Gear %in% c("Gillnets", "Seine_Danish_and_Other","Trawl_Midwater_or_Unsp")) %>% 
  filter(!(Gear =="Trawl_Midwater_or_Unsp" & Length_Category =="12-24m")) %>% 
  mutate(Year = as.integer(Year))
  
unique(effort_gear_filt$Gear)

range(effort_gear_filt$EffActive)

unique(effort_gear_filt$Sector)

# tidying to obtain total effort by fleet by year 

eff_tidy = effort_gear_filt %>% 
  group_by(Year, 
           # Gear, 
           Sector) %>% 
  summarize(Efforteff = sum(EffActive, na.rm=TRUE),
            Effortnom = sum(NomActive, na.rm=TRUE)) 

eff_art = eff_tidy %>% 
  filter(Sector != "I") %>% 
  group_by(Year) %>% 
  summarize(Efforteff = sum(Efforteff, na.rm=TRUE),
            Effortnom = sum(Effortnom, na.rm=TRUE)) %>% 
  mutate(Sector = "Art")

eff_bound = eff_tidy %>% 
  filter(Sector == "I") %>% 
  group_by(Year) %>% 
  summarize(Efforteff = sum(Efforteff, na.rm=TRUE),
            Effortnom = sum(Effortnom, na.rm=TRUE)) %>% 
  mutate(Sector = "I") %>% 
  rbind(eff_art)

ggplot(data = eff_bound, aes(x = Year, y = Effortnom, color = Sector) ) + 
  geom_line() + 
  facet_wrap(~Sector, scales = "free")
```

## Looking at just days at sea so that I can compare to the FAO data's effort

```{r}
effort_days = effort_filt %>% 
  mutate(effdays = NomActive/P)

effort_gear_filt = effort_days %>% 
  filter(Gear %in% c("Gillnets", "Seine_Danish_and_Other","Trawl_Midwater_or_Unsp")) %>% 
  filter(!(Gear =="Trawl_Midwater_or_Unsp" & Length_Category =="12-24m")) %>%
  mutate(Year = as.integer(Year))
options(scipen=999)
range(effort_gear_filt$NomActive)

range(effort_gear_filt$P)

# tidying to obtain total effort by fleet by year 

eff_tidy = effort_gear_filt %>% 
  group_by(Year, 
           # Gear,
           Sector) %>% 
  summarize(Effortday = sum(effdays, na.rm=TRUE),
            Effortnom = sum(NomActive, na.rm=TRUE)) 

eff_art = eff_tidy %>% 
  filter(Sector != "I") %>% 
  group_by(Year) %>% 
  summarize(Effortday = sum(Effortday, na.rm=TRUE),
            Effortnom = sum(Effortnom, na.rm=TRUE)) %>% 
  mutate(Sector = "Art")

eff_bound = eff_tidy %>% 
  filter(Sector == "I") %>% 
  group_by(Year) %>% 
  summarize(Effortday = sum(Effortday, na.rm=TRUE),
            Effortnom = sum(Effortnom, na.rm=TRUE)) %>% 
  mutate(Sector = "I") %>% 
  rbind(eff_art)

ggplot(data = eff_bound, aes(x = Year, y = Effortday, color = Sector) ) +
  geom_line() + 
  facet_wrap(~Sector, scales = "free")

```

## Comparing the mapped effort data to FAO catch data to see if CPUE tracks...

```{r}
all_filtered = all_metrics %>% 
  filter(Year >= 2003)

eff_join = eff_bound %>% 
  mutate(Sector = case_when(
    Sector == "I" ~ "Industrial",
    Sector == "Art" ~ "Artisanal"
  )) %>% 
  rename(Fleet = Sector)

combined = all_filtered %>% 
  left_join(eff_join, by = c("Year", "Fleet")) %>% 
  mutate(CPUE_new = Catch_tonnes/Effortday,
         CPUE_diff = CPUE_new-CPUE)

## The difference between CPUE's does not look too large, especially for the Artisanal fishers. This might be because my brain is tired but im comfortable with this difference. 
```


```{r}
library(readr)
SAU_EEZ_430_v50_1 <- read_csv(here::here("data_raw/data_SAU/SAU EEZ 430 v50-1.csv"))
View(SAU_EEZ_430_v50_1)


sardinellas <- SAU_EEZ_430_v50_1 %>% 
  mutate(filters = if_else(str_detect(scientific_name, "Sardinella"), 1, 0)) %>% 
  filter(filters %in% c(1)) %>% 
  filter(year >= 2003) %>% 
  filter(gear_type %in% c("small scale seine nets", "subsistence fishing gear", "pelagic trawl", "artisanal fishing gear", "small scale gillnets", "bottom trawl")) %>% 
  filter(fishing_entity %in% c("China", "Liberia")) %>% 
  filter(catch_type != "Discards") %>% 
  group_by(year, fishing_entity) %>% 
  summarize(catch_tonnes = sum(tonnes, na.rm=TRUE),
            value = sum(landed_value, na.rm=TRUE)) %>% 
  mutate(price_per_tonne = value / catch_tonnes)

price = sardinellas %>% 
  group_by(year) %>% 
  summarize(price = mean(price_per_tonne))

mean(price$price)
sd(price$price)
unique(sardinellas$fishing_entity)
```

