---
title: "FishstatJ Data Inspection"
author: "Dustin Duncan"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(here)
```

```{r}
fishstatj <- read.csv(here("Data/Other/FishstatJ_Liberia_capture_production.csv")) %>% 
  janitor::clean_names()
unique(fishstatj$fao_division_name)
fishstatj_tuna <- fishstatj %>% 
  filter(fao_division_name == "Tunas (CECAF area)")

tuna_l <- fishstatj_tuna %>% 
  filter(asfis_species_name == "Albacore" | asfis_species_name == "Bigeye tuna" | asfis_species_name == "Bullet tuna" | asfis_species_name == "Frigate and bullet tunas" | asfis_species_name == "Frigate tuna" | asfis_species_name == "Little tunny(=Atl.black skipj)" | asfis_species_name == "Skipjack tuna" | asfis_species_name == "Yellowfin tuna") %>% 
  pivot_longer(cols = c(x_1970, x_1971,x_1972,x_1973,x_1974,x_1975,x_1976,x_1977,x_1978,x_1979,x_1980,x_1981,x_1982,x_1983,x_1984,x_1985,x_1986,x_1987,x_1988,x_1989,x_1990,x_1991,x_1992,x_1993,x_1994,x_1995,x_1996,x_1997,x_1998,x_1999,x_2000,x_2001,x_2002,x_2003,x_2004,x_2005,x_2006,x_2007,x_2008,x_2009,x_2010,x_2011,x_2012,x_2013,x_2014,x_2015,x_2016,x_2017,x_2018,x_2019,x_2020,x_2021), names_to = "year", values_to = "tons") %>% 
  select(-c(s, s_1, s_2, s_3, s_4, s_5, s_6, s_7, s_8, s_9, s_10, s_11, s_12, s_13, s_14, s_15, s_16, s_17, s_18, s_19, s_20, s_21, s_22, s_23, s_24, s_25, s_26, s_27, s_28, s_29, s_30, s_31, s_32, s_33, s_34, s_35, s_36, s_37, s_38, s_39, s_40, s_41, s_42, s_43, s_44, s_45, s_46, s_47, s_48, s_49, s_50, s_51))

tuna_l2 <- fishstatj_tuna %>% 
  filter(asfis_species_name == "Albacore" | asfis_species_name == "Bigeye tuna" | asfis_species_name == "Bullet tuna" | asfis_species_name == "Frigate and bullet tunas" | asfis_species_name == "Frigate tuna" | asfis_species_name == "Little tunny(=Atl.black skipj)" | asfis_species_name == "Skipjack tuna" | asfis_species_name == "Yellowfin tuna") %>% 
  select(c(asfis_species_name, s, s_1, s_2, s_3, s_4, s_5, s_6, s_7, s_8, s_9, s_10, s_11, s_12, s_13, s_14, s_15, s_16, s_17, s_18, s_19, s_20, s_21, s_22, s_23, s_24, s_25, s_26, s_27, s_28, s_29, s_30, s_31, s_32, s_33, s_34, s_35, s_36, s_37, s_38, s_39, s_40, s_41, s_42, s_43, s_44, s_45, s_46, s_47, s_48, s_49, s_50, s_51)) %>% 
  pivot_longer(cols = c(-asfis_species_name), names_to = "year_estimate", values_to = "type") %>% 
  select(type)

tuna_longer <- cbind(tuna_l, tuna_l2) %>% 
  mutate(year = str_replace_all(year, pattern = "x_", replacement = ""),
         year = as.integer(year)) %>% 
  mutate(asfis_species_name = ifelse(asfis_species_name == "Little tunny(=Atl.black skipj)", "Little tunny", asfis_species_name))

unique(tuna_longer$asfis_species_name)
ggplot(data = tuna_longer, aes(x = year, y = tons, color = asfis_species_name)) + 
  geom_line()
```
